// This file was autogenerated.
    import core from "@actions/core";

    export interface InputParameters {
        /**
         * The workflow id.
         */
        workflow_id: string;
        /**
         * The repository to look for workflows.
         */
        repository: string;
        /**
         * The branch to check on. Defaults to all branches.
         */
        branch: string;
    }

    export function getInputParameters(): InputParameters {
        return {
            workflow_id: core.getInput("workflow_id", { required: true }),
            repository: core.getInput("repository", { required: true }),
            branch: core.getInput("branch", { required: false }) || "",
        };
    }
    