on:
  push:
    paths:
      - ".github/workflows/update-artifacts.yml"
      - "src/**/*"
      - "dist/**/*"
      - ".nvmrc"
      - "package.json"
      - ".yarnrc"
      - "yarn.lock"
      - "rollup.config.js"
      - "tsconfig.json"
      - "action.yml"

jobs:
  update-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn -s --frozen-lockfile

      - run: yarn -s generate
      - run: yarn -s build

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --cached --quiet HEAD || git commit -m "[automated] Update artifacts"

      - name: Push changes
        uses: ambimax/action-github-push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          force: true
